// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fghkifpvajvsmohiaxpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnaGtpZnB2YWp2c21vaGlheHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDkzNTYsImV4cCI6MjA2NDYyNTM1Nn0.RC4G2_Hcmf7EKvA2gggRzvNG8NDdEn6cgOeVMRrric0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);